[package]
name = "crow"
version = "0.1.0"
authors = ["dalesnail <cameronmills.work@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
clap = "2"
open = "1.2.2"
directories = "2.0"
fs_extra = "1.1.0"
